spring:
  application:
    name: 出入境动态管理监测系统

  profiles:
    active: dev

  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
    favicon:
      enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true


logging:
  config: classpath:logback-boot.xml

mybatis:
  mapper-locations: classpath*:cn/xiongdi/ocdm/mapper/mapping/*.xml
  type-aliases-package: cn.xiongdi.ocdm.mapper.dao

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

param:
  noauth-url: /login.html,/webapi/sign/login,/webapi/sign/confirmUserInfo,/webapi/sign/resetPassword
  home-url: /home.html,/index.html,/header.html,/nav.html,/passportExaApproval.html,/passportLendApply.html,
              /webapi/sign/loginOut,/webapi/sign/resetPassword,/webapi/home/getLoginInfo,/webapi/home/updateUserLxdh,
              /webapi/sign/getMenuTreeByRole,/webapi/needToDo/getNeedToDoCount,/webapi/PassPortExaApp/getCerPassPortInfo,
              /webapi/PassPortExaApp/getCerBorrowProcessInfo,/webapi/PassPortExaApp/auditPassThrough,
              /webapi/PassPortExaApp/auditPassNotThrough,/webapi/PassPortExaApp/auditTurnWrong,
              /webapi/SendBack/getCerPassPortInfo,/webapi/SendBack/getPamCauseInfo,
              /webapi/SendBack/getSysOrganizationInfo,/webapi/SendBack/getPamCauseMaterialInfo,
              /webapi/SendBack/saveProcess,/webapi/SendBack/commitProcess,
              /webapi/SendBack/getCerBorrowProcessInfo,/webapi/SendBack/getCerGrantReturn,
              /webapi/SendBack/getCerProcesOpinion,/webapi/SendBack/uploadFile,/webapi/SendBack/getProcessmaterial,
              /webapi/SendBack/downLoad